name: Connect a GitHub runner to an AKS cluster

on:
  workflow_dispatch:
    inputs:
      runnerTags:
        description: 'The tags for the runner to connect to the AKS cluster.'
        required: true
      resourceGroup:
        description: 'The resource group of the AKS cluster.'     
        required: true 
      clusterName:
        description: 'The name of the AKS cluster.'
        required: true
        
jobs:   
  deploy:
    name: Connect Runner to AKS  Cluster
    runs-on: [${{ github.events.inputs.runnerTags }}]
    
    steps:
    
     - name: Azure Login
       run: az login --identity

     - name: Set Azure Subscription
       run: az account set --subscription "f2f53eaa-44eb-4a72-9270-130f0c9f1582"  
       
     - name: Connect To Cluster
       run: az aks get-credentials --resource-group ${{ github.event.inputs.resourceGroup }} --name ${{ github.event.inputs.clusterName }}
