name: Connect a GitHub runner to an AKS cluster

on:
  workflow_dispatch:
    inputs:
     userName:
        description: 'The username to create the tools under on the GitHub Runner vm'     
        default: 'etpAdmin'
        required: false
      resourceGroup:
        description: 'The resource group of the AKS cluster.'     
        required: true 
      clusterName:
        description: 'The name of the AKS cluster.'
        required: true
        
jobs:   
  deploy:
    name: Connect Runner to AKS  Cluster
    runs-on: [dmz-runner]
    
    steps:
    
     - name: Azure Login
       run: sudo -u ${{ github.event.inputs.userName }} -i az login --identity

     - name: Set Azure Subscription
       run: sudo -u ${{ github.event.inputs.userName }} -i az account set --subscription "f2f53eaa-44eb-4a72-9270-130f0c9f1582"  
       
     - name: Connect To Cluster
       run: sudo -u ${{ github.event.inputs.userName }} -i az aks get-credentials --resource-group ${{ github.event.inputs.resourceGroup }} --name ${{ github.event.inputs.clusterName }}
