name: Connect a GitHub runner to an AKS cluster

on:
  workflow_dispatch:
    inputs:
      runnerUserName:
        description: 'The username to run the commands on.'
        default: etpAdmin
        required: false
      subscriptionId:
        description: 'The subscription id that the resources live on.'
        default: 'f2f53eaa-44eb-4a72-9270-130f0c9f1582'
        required: false
      resourceGroup:
        description: 'The resource group of the AKS cluster.'     
        required: true 
      clusterName:
        description: 'The name of the AKS cluster.'
        required: true
        
jobs:   
  deploy:
    name: Connect Runner to AKS  Cluster
    runs-on: [dmz-runner]
    
    steps: 
     - name: Azure Login
       run: sudo -u ${{ github.event.inputs.runnerUserName }} -i az login --identity

     - name: Get VM Username and Password from KeyVault      
       uses: Azure/get-keyvault-secrets@v1.0
       id: userCredentials
       with:
          keyvault: ${{ steps.env-variables.outputs.userCredentialsKeyVaultName }}
          secrets: "apiGatewayRunnerUsername"
          
     - name: Set Azure Subscription
       run: sudo -u ${{ steps.userCredentials.outputs.apiGatewayRunnerUsername }} -i az account set --subscription ${{ github.event.inputs.subscriptionId }} 
       
     - name: Connect To Cluster
       run: sudo -u ${{ steps.userCredentials.outputs.apiGatewayRunnerUsername }} -i az aks get-credentials --resource-group ${{ github.event.inputs.resourceGroup }} --name ${{ github.event.inputs.clusterName }}
