name: Deploy Github Runner VM Infrastructure

# This can be refactored once the naming conventions for DP 2.0 are put into place as we should no longer need to ask for the resource group name or resource name of the nsg/dmz
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment name where configuration is stored'     
        required: true 
      githubRepoUrl:
        description: 'The repository to link the Github runner to.'
        required: true
      githubRepoToken:
        description: 'The token to set up the Github runner.'
        required: true
      githubRunnerLabels:
        description: 'A comma seperated list of labels to associate with the Github runner.'
        default: 'dmz-runner'
        required: false

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
jobs:
  deploy:
    name: Deploy GitHub Runner Infrastructure
    runs-on: [ubuntu-latest]
    
    steps:       
    - name: Checkout Etp Infra Repo
      uses: actions/checkout@v2  
      
    - name: Checkout Action Get Variables Repo
      uses: actions/checkout@v2
      with:
          repository: ETP-Cloud/action-get-variables
          token: ${{ secrets.ETP_GITHUB_TOKEN }}
          path: etp-get-vars
            
    - name: Get variables from config/${{ github.event.inputs.env }}/deploy-ghr-infra
      id: env-variables
      uses: ./etp-get-vars
      with: 
          variable-set: 'config/${{ github.event.inputs.env }}/deploy-ghr-infra'

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # Azure Service Principle

    - name: Set Azure Subscription
      run: az account set --subscription ${{ steps.env-variables.outputs.subscriptionId }} 

    - name: Get VM Username and Password from KeyVault      
      uses: Azure/get-keyvault-secrets@v1.0
      id: userCredentials
      with:
          keyvault: ${{ steps.env-variables.outputs.userCredentialsKeyVaultName }}
          secrets: "apiGatewayRunnerUsername, apiGatwayRunnerPassword"

    - name: Update ARM parameters file with values from config file
      uses: microsoft/variable-substitution@v1
      id: parameters-file-replacement
      with:
        files: "templates/shared/dmz-gh-runner/vm-creation.parameters.json"
      env:
        parameters.prefix.value: ${{ steps.env-variables.outputs.prefix }}
        parameters.env.value: ${{ steps.env-variables.outputs.env }}
        parameters.adminUsername.value: ${{ steps.userCredentials.outputs.apiGatewayRunnerUsername }}
        parameters.adminPassword.value: ${{ steps.userCredentials.outputs.apiGatwayRunnerPassword }}
        parameters.dmzResourceGroupName.value: ${{ steps.env-variables.outputs.dmzResourceGroupName }}
        parameters.dmzVNetResourceName.value: ${{ steps.env-variables.outputs.dmzVNetResourceName }}
        parameters.ghRunnerNSGResourceName.value: ${{ steps.env-variables.outputs.ghRunnerNSGResourceName }}
        parameters.githubRepoUrl.value: ${{ github.event.inputs.githubRepoUrl }}
        parameters.githubRepoToken.value: ${{ github.event.inputs.githubRepoToken }}
        parameters.githubRunnerConfigurationScriptUri.value: ${{ steps.env-variables.outputs.githubRunnerConfigurationScriptRawUri }}?token=${{ secrets.GH_RUNNER_CONFIG_SCRIPT_RAW_TOKEN }}
        parameters.githubRunnerLabels.value: ${{ github.events.input.githubRunnerLabels }}
        
    - name: Create Resource Group
      run: az group create --name etp-rg-ghr-tsl --location "East US"    

    - name: Deploy Arm Template
      uses: azure/arm-deploy@v1
    
      with:
        scope: subscription     
        subscriptionId: ${{ steps.env-variables.outputs.subscriptionId }} 
        template: "templates/shared/dmz-gh-runner/vm-creation.template.json"
        parameters: "templates/shared/dmz-gh-runner/vm-creation.parameters.json"
        deploymentMode: Incremental
        deploymentName: Create_Github_Runner_VM_Infra
