name: Deploy Github Runner VM Infrastructure

on:
  workflow_dispatch:
    inputs:
      prefix:
        description: 'Prefix added to azure resources names to be globally unique (lowercase only).'     
        default: 'etp'
        required: false
      env:
        description: 'Target environment (dev, int...) Suffix added to azure resources names to be globally unique (lowercase only).'     
        required: false 
        default: 'tsl'
      adminUsername:
        description: 'The admin username that will be used to log onto the runner vm.'     
        required: false
        default: 'etpAdmin'
      adminPassword:
        description: 'The admin password that will be used to log onto the runner vm.'
        required: false
        default: 'etpGHRunnerVM!!'
      dmzVNetSubscriptionId:
        description: 'The subscription Id that the DMZs VNet is on.'
        required: false
        default: 'f2f53eaa-44eb-4a72-9270-130f0c9f1582'
      dmzVNetResourceGroupName:
        description: 'The resource group name that the DMZ Vnet is in.'
        required: false
        default: 'etp-dp-dev-na-eastus-dmz'
      dmzVNetResourceName:
        description: 'The name of the DMZ resource.'
        required: false
        default: 'dp-dev-na-eastus-dmz-vnet'
      ghRunnerNSGResourceName:
        description: 'The name of the GitHub Runner VMs NSG resource.'
        required: false
        default: 'dp-dev-na-eastus-ghrunner-vm-subnet-nsg'
      githubRepoUrl:
        description: 'The repository to link the GitHub runner to.'
        required: true
      githubRepoToken:
        description: 'The token to set up the GitHub runner.'
        required: true

jobs:
  deploy-github-runner-resources:
    runs-on: [self-hosted]
    name: Deploy Github Runner Resources

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2   
        
      - name: Set the values in parameters file
        uses: microsoft/variable-substitution@v1
        id: parameters-file-replacement
        with:
          files: "templates/shared/dmz-gh-runner/vm-creation.parameters.json"
        env:
          parameters.prefix.value: ${{ github.event.inputs.prefix }}
          parameters.env.value: ${{ github.event.inputs.env }}
          parameters.adminUsername.value: ${{ github.event.inputs.adminUsername }}
          parameters.adminPassword.value: ${{ github.event.inputs.adminPassword }}
          parameters.dmzVNetSubscriptionId.value: ${{ github.event.inputs.dmzVNetSubscriptionId }}
          parameters.dmzVNetResourceGroupName.value: ${{ github.event.inputs.dmzVNetResourceGroupName }}
          parameters.dmzVNetResourceName.value: ${{ github.event.inputs.dmzVNetResourceName }}
          parameters.ghRunnerNSGSubscriptionId.value: ${{ github.event.inputs.dmzVNetSubscriptionId }}
          parameters.ghRunnerNSGResourceGroupName.value: ${{ github.event.inputs.dmzVNetResourceGroupName }}
          parameters.ghRunnerNSGResourceName.value: ${{ github.event.inputs.ghRunnerNSGResourceName }}
          parameters.githubRepoUrl.value: ${{ github.event.inputs.githubRepoUrl }}
          parameters.githubRepoToken.value: ${{ github.event.inputs.githubRepoToken }}
          parameters.githubRunnerConfigurationScriptUri.value: ${{ github.event.inputs.githubRunnerConfigurationScriptUri }}

      - name: Azure Login
        run: az login --identity

      - name: Set Azure Subscription
        run: az account set --subscription "f2f53eaa-44eb-4a72-9270-130f0c9f1582"  

      - name: Create Resource Group
        run: az group create --name etp-rg-ghr-tsl --location "East US"    

      - name: Checkout Arm Template
        uses: azure/arm-deploy@v1
      
        with:        
          resourceGroupName: etp-rg-ghr-tsl
          template: "templates/shared/dmz-gh-runner/vm-creation.template.json"
          parameters: "templates/shared/dmz-gh-runner/vm-creation.parameters.json"
          deploymentMode: Incremental
          deploymentName: Create_GitHub_Runner_VM_Infra