name: Install GitHub Runner Dependencies

on:
  workflow_dispatch:
   
jobs:   
  initialize:
    runs-on: [dmz-runner]
    
    defaults:
      run:
        working-directory:  /home/etpAdmin/
        
    steps:
      - name: Update and Upgrade
        run: sudo apt update -y && sudo apt upgrade -y
        
      - name: test
        run: sudo -i -H -u etpAdmin
        
      - name: Install Homebrew
        run: echo whoami;
             mkdir ~/.linuxbrew/bin;
             git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew;
             ln -s ../Homebrew/bin/brew ~/.linuxbrew/bin;
             eval $(~/.linuxbrew/bin/brew shellenv)
        
      - name: Install Azure cli
        run: brew install azure-cli
                
      - name: Install Node
        run: brew install node
        
      - name: Install Helm
        run: brew install helm
        
      - name: Install KubeCtl
        run: brew install kubectl
        
      - name: Install GlooCtl
        run: brew install glooctl
        
      - name: Install Go
        run: brew install go
