name: Install GitHub Runner Dependencies

on:
  workflow_dispatch:

jobs:   
  updateSystem:
    name: Update and Upgrade apt
    runs-on: [dmz-runner]
    
    steps:
     - name: Update and Upgrade
       run: sudo apt update -y && sudo apt upgrade -y

  installHomebrew:
    name: Install Homebrew
    runs-on: [dmz-runner]
    needs: [updateSystem] 
    defaults:
      run:
        working-directory:  /home/etpAdmin/
        
    steps:
      - name: Install Homebrew sliently
        run: sudo apt install linuxbrew-wrapper -y
        
      - name: Run brew for the first time to create the .linuxbrew directory
        run: sudo -u etpAdmin -i brew -h
        
      - name: Test that linuxbrew exists and update the shell path with it
        run: test -d /home/etpAdmin/.linuxbrew && eval $(/home/etpAdmin/.linuxbrew/bin/brew shellenv)
             
      - name: Update etpAdmins profile 
        run: test -r /home/etpAdmin/.profile && echo "eval $(/home/etpAdmin/.linuxbrew/bin/brew shellenv)" >>/home/etpAdmin/.profile
        
        
  installTools:
    name: Install tools
    runs-on: [dmz-runner]
    needs: [installHomebrew]
    defaults:
      run:
        working-directory:  /home/etpAdmin/    

    steps:
      - name: Install Azure cli
        run: sudo -u etpAdmin -i brew install azure-cli

      - name: Install Node
        run: sudo -u etpAdmin -i brew install node

      - name: Install Helm
        run: sudo -u etpAdmin -i brew install helm

      - name: Install KubeCtl
        run: sudo -u etpAdmin -i brew install kubectl

      - name: Install GlooCtl
        run: sudo -u etpAdmin -i brew install glooctl

      - name: Install Go
        run: sudo -u etpAdmin -i brew install go
        
  validateTools:
      name: Validate Tools are Installed
      runs-on: [dmz-runner]
      needs: [installTools]
      
      steps:
      - name: Validate Azure cli is installed
        run: sudo -u etpAdmin -i az -v

      - name: Validate Node is installed
        run: sudo -u etpAdmin -i node -v

      - name: Validate Helm is installed
        run: sudo -u etpAdmin -i helm version

      - name: Validate KubeCtl is installed
        run: sudo -u etpAdmin -i kubectl version

      - name: Validate GlooCtl is installed
        run: sudo -u etpAdmin -i glooctl version

      - name: Validate Go is installed
        run: go version

