name: Install GitHub Runner Dependencies

on:
  workflow_dispatch:
   
jobs:   
  initialize:
    runs-on: [dmz-runner]
    
    defaults:
      run:
        working-directory:  /home/etpAdmin/
        
    steps:
      - name: Update and Upgrade
        run: sudo apt update -y && sudo apt upgrade -y
        
      - name: Clone Homebrew
        run: sudo -i -H -u etpAdmin git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew;
        
    
