name: Install GitHub Runner Dependencies

on:
  workflow_dispatch:
   
jobs:   
  initialize:
    runs-on: [dmz-runner]
    
    defaults:
      run:
        working-directory:  /home/etpAdmin/
        
    steps:
      - name: Update and Upgrade
        run: sudo apt update -y && sudo apt upgrade -y
           
      - name: Test
        run: sudo -i -H -u etpAdmin
        
      - name: Install Homebrew
        run:  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        
      - name: Create a symbolic linx to the bin dir
        run: test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
         
      - name: Test the shell
        run: test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
                
      - name: Test the shell
        run: test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
        
      - name: Test the shell
        run: echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile

        
      - name: Install Azure cli
        run: brew install azure-cli
                
      - name: Install Node
        run: brew install node
        
      - name: Install Helm
        run: brew install helm
        
      - name: Install KubeCtl
        run: brew install kubectl
        
      - name: Install GlooCtl
        run: brew install glooctl
        
      - name: Install Go
        run: brew install go
