# This workflow prefixes most commands with sudo -u <username> -i to ensure that the commands are run under the correct user.
# Without this prefix any command will try to run under the root user (which is the user that the Self-Hosted runner works under).

name: Install Github Runner Dependencies

on:
  workflow_dispatch:
     inputs:
      userName:
        description: 'The username to create the tools under on the Github Runner vm'     
        default: 'etpAdmin'
        required: false
        
jobs:   
  updateSystem:
    name: Update and Upgrade apt
    runs-on: [dmz-runner]
    
    steps:
     - name: Update and Upgrade
       run: sudo apt update -y && sudo apt upgrade -y

  setRBACPermissions:
    name: Set RBAC Permissions to grant VM AKS access
    runs-on: [dmz-runner]
    
    steps:
      - name: Azure Login
        uses: az login --identity

      - name: Set Azure Subscription
        run: az account set --subscription f2f53eaa-44eb-4a72-9270-130f0c9f1582
        
      - name: Set RBAC permissions
        run: az vm identity assign -g etp-rg-ghr-tsl -n etp-vm-ghr-tsl --role '/subscriptions/f2f53eaa-44eb-4a72-9270-130f0c9f1582/providers/Microsoft.Authorization/roleDefinitions/4abbcc35-e782-43d8-92c5-2d3f1bd2253f' --scope '/subscriptions/f2f53eaa-44eb-4a72-9270-130f0c9f1582'
      
  installHomebrew:
    name: Install Homebrew
    runs-on: [dmz-runner]
    needs: [updateSystem] 
    defaults:
      run:
        working-directory:  /home/${{ github.event.inputs.userName }}/
        
    steps:
      - name: Install Homebrew sliently
        run: sudo apt install linuxbrew-wrapper -y
        
      - name: Run brew for the first time to create the .linuxbrew directory
        run: sudo -u ${{ github.event.inputs.userName }} -i brew -h
        
      - name: Test that linuxbrew exists and update the shell path with it
        run: test -d /home/${{ github.event.inputs.userName }}/.linuxbrew && eval $(/home/${{ github.event.inputs.userName }}/.linuxbrew/bin/brew shellenv)
             
      - name: Update etpAdmins profile 
        run: test -r /home/${{ github.event.inputs.userName }}/.profile && echo "eval $(/home/${{ github.event.inputs.userName }}/.linuxbrew/bin/brew shellenv)" >>/home/${{ github.event.inputs.userName }}/.profile
        
  installTools:
    name: Install tools
    runs-on: [dmz-runner]
    needs: [installHomebrew]
   
    steps:
      - name: Install Azure cli
        run: sudo -u ${{ github.event.inputs.userName }} -i brew install azure-cli

      - name: Install Node
        run: sudo -u ${{ github.event.inputs.userName }} -i brew install node

      - name: Install Helm
        run: sudo -u ${{ github.event.inputs.userName }} -i brew install helm

      - name: Install KubeCtl
        run: sudo -u ${{ github.event.inputs.userName }} -i brew install kubectl

      - name: Install GlooCtl
        run: sudo -u ${{ github.event.inputs.userName }} -i brew install glooctl

      - name: Install Go
        run: sudo -u ${{ github.event.inputs.userName }} -i brew install go
        
  validateTools:
      name: Validate Tools are Installed
      runs-on: [dmz-runner]
      needs: [installTools]
      
      # This is a very basic way to validate. We should add some more logic here to validate tools are specific versions.
      steps:
      - name: Validate Azure cli is installed
        run: sudo -u ${{ github.event.inputs.userName }} -i az -v

      - name: Validate Node is installed
        run: sudo -u ${{ github.event.inputs.userName }} -i node -v

      - name: Validate Helm is installed
        run: sudo -u ${{ github.event.inputs.userName }} -i helm version

        # instead of doing a version check with kubectl do a help check to validate it's installed.
        # at this point kubectl isnt connected to a cluster so kubectl version returns an exit code of 1 which fails this step
      - name: Validate KubeCtl is installed
        run: sudo -u ${{ github.event.inputs.userName }} -i kubectl --help

      - name: Validate GlooCtl is installed
        run: sudo -u ${{ github.event.inputs.userName }} -i glooctl version

      - name: Validate Go is installed
        run: sudo -u ${{ github.event.inputs.userName }} -i go version

