name: Install GitHub Runner Dependencies

on:
  workflow_dispatch:
   
jobs:   
  initialize:
    runs-on: [dmz-runner]
    
    defaults:
      run:
        working-directory:  /home/etpAdmin/
        
    steps:
      - name: Update and Upgrade
        run: sudo apt update -y && sudo apt upgrade -y
                   
      - name: Install Homebrew
        run: sudo -u etpAdmin mkdir ~/.linuxbrew/bin;
             sudo -u etpAdmin git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew;
             sudo -u etpAdmin ln -s ../Homebrew/bin/brew ~/.linuxbrew/bin;
             sudo -u etpAdmin eval $(~/.linuxbrew/bin/brew shellenv)
        
      - name: Install Azure cli
        run: sudo -u etpAdmin brew install azure-cli
                
      - name: Install Node
        run: sudo brew install node
        
      - name: Install Helm
        run: sudo -u etpAdmin brew install helm
        
      - name: Install KubeCtl
        run: sudo -u etpAdmin brew install kubectl
        
      - name: Install GlooCtl
        run: sudo -u etpAdmin brew install glooctl
        
      - name: Install Go
        run: brew install go
