name: Install GitHub Runner Dependencies

on:
  workflow_dispatch:
   
jobs:   
  initialize:
    runs-on: [dmz-runner]
    defaults:
      run:
        working-directory:  /home/etpAdmin/
        
    steps:
      - name: Update and Upgrade
        run: sudo apt update -y && sudo apt upgrade -y
        
      - name: Login as user
        run: sudo -i -u etpAdmin
        
      - name: Install Homebrew
        run: sudo apt install linuxbrew-wrapper -y
        
      - name: Update path for homebrew
        run: export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin${PATH+:$PATH}"
             export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew";
             export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar";
             export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew";
             export MANPATH="/home/linuxbrew/.linuxbrew/share/man${MANPATH+:$MANPATH}:";
             export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:${INFOPATH:-}";
        
      - name: Install Azure cli
        run: brew install azure-cli
                
      - name: Install Node
        run: brew install node
        
      - name: Install Helm
        run: brew install helm
        
      - name: Install KubeCtl
        run: brew install kubectl
        
      - name: Install GlooCtl
        run: brew install glooctl
        
      - name: Install Go
        run: brew install go
