name: Install GitHub Runner Dependencies

on:
  workflow_dispatch:
   
jobs:   
  initialize:
    runs-on: [dmz-runner]
    
    defaults:
      run:
        working-directory:  /home/etpAdmin/
        
    steps:
      - name: Update and Upgrade
        run: sudo apt update -y && sudo apt upgrade -y
        
      - name: Clone Homebrew
        run: sudo apt install linuxbrew-wrapper -y
        
      - name: check brew
        run: sudo -u etpAdmin brew -h
        
      - name: Install Azure cli
        run: sudo -u etpAdmin brew install azure-cli
                
      - name: Install Node
        run: brew install node
        
      - name: Install Helm
        run: brew install helm
        
      - name: Install KubeCtl
        run: brew install kubectl
        
      - name: Install GlooCtl
        run: brew install glooctl
        
      - name: Install Go
        run: brew install go
    
