name: Set Upstream TLS on a specified route

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Add certificate to K8s cert store
        run: kubectl create secret tls petstore-secret --key "C:\Users\dspAdmin\Desktop\wildcard-cert for syseng\wildcard-syseng.struxurewarecloud.com.key" --cert "C:\Users\dspAdmin\Desktop\wildcard-cert for syseng\wildcard-syseng.struxurewarecloud.com.crt" --namespace gloo-system

      - name: Set VirtualService to reference new secret
        run: glooctl edit vs --name default-petstore-8080 --namespace gloo-system --ssl-secret-name petstore-secret --ssl-secret-namespace gloo-system
