name: Deploy Github Runner Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy-github-runner-resources:
    runs-on: [self-hosted]
    name: Deploy Github Runner Resources

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2   
        
      - name: Set the values in parameters file
        uses: microsoft/variable-substitution@v1
        id: parameters-file-replacement
        with:
          files: "templates/shared/dmz-gh-runner/vm-creation.parameters.json"
        env:
          parameters.prefix.value: etp
          parameters.env.value: tsl
          parameters.adminUsername.value: etpAdmin
          parameters.adminPassword.value: etpGHRunnerVM!!
          parameters.dmzVNetSubscriptionId.value: f2f53eaa-44eb-4a72-9270-130f0c9f1582
          parameters.dmzVNetResourceGroupName.value: etp-dp-dev-na-eastus-dmz
          parameters.dmzVNetResourceName.value: dp-dev-na-eastus-dmz-vnet
          parameters.ghRunnerNSGSubscriptionId.value: f2f53eaa-44eb-4a72-9270-130f0c9f1582
          parameters.ghRunnerNSGResourceGroupName.value: etp-dp-dev-na-eastus-dmz
          parameters.ghRunnerNSGResourceName.value: dp-dev-na-eastus-ghrunner-vm-subnet-nsg

      - name: Azure Login
        run: az login --identity

      - name: Set Azure Subscription
        run: az account set --subscription "f2f53eaa-44eb-4a72-9270-130f0c9f1582"       

      - name: Checkout Arm Template
        uses: azure/arm-deploy@v1
        with:        
          resourceGroupName: etp-rg-ghr-tsl
          template: "templates/shared/dmz-gh-runner/vm-creation.template.json"
          parameters: "templates/shared/dmz-gh-runner/vm-creation.parameters.json"
          deploymentMode: Incremental
          deploymentName: Create GitHub Runner Infra
